<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  0 => '',
  'allow everyone, even guests, to see user profiles' => 'permetti a tutti, anche ai guest, di vedere i profili degli utenti',
  'allow user registration' => 'permetti la registrazione utenti',
  'if a user has on a controller admin permissions will have access to write and read pages. If he has write permissions will also have access to read pages' => 'se un utente ha su un controller i permessi di admin avr&agrave; accesso anche alle pagine che richiedono write e read, se ha invece i permessi di write avr&agrave; accesso anche alle pagine di read.',
  'if true users just have to provide user and email to reset their password.<br/>Otherwise they will have to answer their custom question' => 'se &egrave; settato su TRUE gli utenti devono solo dare username e indirizzo email per resettare la propria password, altrimenti gli sar&agrave; chiesta anche la domanda di sicurezza',
  'if true when a user creates an account a mail with an activation code will be sent to his email address' => 'se &egrave; settato su TRUE quando un utente crea un account una mail con un codice di attivazione gli sar&agrave; inviata al suo indirizzo email',
  'if true when a user creates an account a user with user admin rights will have to approve the registration.<br/>If both this setting and user_need_activation are true the user will need to activate is account first and then will need the approval' => 'se &egrave; settato su TRUE quando un utente crea un account un utente con permessi di admin dovr&agrave; approvare la sua registrazione.<br/>Se sia questo settaggio che user_need_activation sono settati su TRUE allora l\'utente dovr&agrave; prima attivare l\'account e poi questo dovr&agrave; essere approvato.',
  'logged user can see other users profiles' => 'gli utenti loggati possono vedere i profili degli altri utenti',
  'logged users can see the complete user list' => 'gli utenti loggati possono vedere l\'intera lista degli utenti',
  'password strength:<br/>weak: password of at least 5 characters, any character allowed.<br/>
			medium: password of at least 5 characters, must contain at least 2 digits and 2 letters.<br/>
			strong: password of at least 5 characters, must contain at least 2 digits, 2 letters and a special character.' => 'sicurezza della password:<br/>weak: password di almeno 5 caratteri, tutti i caratteri sono permessi.<br/>
  			medium: password di almeno 5 caratteri, deve contenere almeno due numeri e due lettere.<br/>
  			strong: password di almeno 5 caratteri, deve contenere almeno due numeri, due lettere ed un carattere speciale',
  'the group new users automatically belong to' => 'il gruppo di cui fanno parte in automatico i nuovi utenti',
  'userGroups version' => 'versione di userGroups',
  'users can set their own home' => 'gli utenti possono decidere la propria Home',
  'users with just admin write permissions won\'t see the Main Configuration and Cron Jobs panels' => 'gli utenti con solo permessi admin write non potranno vedere il pannello di configurazione e quello dei Cron Jobs',
  'users with userGroups admin admin permission will have access to everything, just like root' => 'gli utenti con permessi admin admin in userGroups avranno accesso a tutto, come Root',
  'if true crons must be executed from the server using a crontab' => 'se settato su TRUE i cronjob dovranno essere eseguiti dal server usando crontab'
);
