<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'view documentation.' => 'legge la documentazione.',
  'can change permission of user and groups whose group level is below his own.' => 'cambia i permessi di gruppi e utenti il cui livello e\' piu\' basso del suo.',
  'can create users and groups and has all the permission of a user with user admin permissions. The level rule still apply.' => 'crea utenti e gruppi ed ha tutti i permessi di un utente con permessi user admin.',
  'can invite other users.' => 'invita altri utenti.',
  'can edit other users, ban them and approve their registrations.' => 'modifca altri utenti, li banna e approva le registrazioni.',
);
