<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'An email containing the instructions to reset your password has been sent to your email address: {email}' => 'Письмо, содержащее инструкции по смене пароля было отправлено на адрес электронной почты, указанный при регистрации.',
  'An invitation email was sent to the address {email}' => 'Приглашение было отправлено на адрес {email}',
  'Creation Date' => 'Дата создания',
  'Impossible to send email to the address {email}' => 'Невозможно отправить письмо по адресу {email}',
  'The activation email was successfully sent to {email}' => 'Письмо с инструкциями по активации акаунта было отправлено на {email}',
  'Update External Profile' => 'Обновление внешнего профиля',
  'A password change has been requested.<br/>You won\'t be able to login until you change the password.' => 'Была запрошена смена пароля.<br/>Вы не можете авторизироваться на сайте пока не измените пароль.',
  'Access' => 'Доступ',
  'Account not active' => 'Учетная запись не активирована',
  'Activate the account' => 'Активация учетной записи',
  'An Error Occurred. Please try later.' => 'Произошла ошибка. Пожалуйста, попробуйте позже.',
  'An email was sent with the instructions to activate your account to the address {email}.' => 'Письмо с инструкциями по активации вашей учетной записи было отправлено на адрес {email}',
  'Approve Registration' => 'Подтверждение регистрации',
  'Ban User' => 'Забанить пользователя',
  'Change Password' => 'Изменение пароля',
  'Confirm Password' => 'Подтверждение пароля',
  'Data Updated Successfully' => 'Данные успешно обновлены',
  'Delete' => 'Удалить',
  'Documentation' => 'Документация',
  'Edit Profile' => 'Изменить профиль',
  'Edit {username}\'s Profile' => 'Изменить профиль {username}',
  'Email' => 'Email',
  'Fields with {*} are required.' => 'Поля отмеченные {*} являются обязательными.',
  'General Info' => 'Основные данные',
  'Group' => 'Группа',
  'Group Level' => 'Уровень группы',
  'Group Name' => 'Имя группы',
  'Groups' => 'Группы',
  'Home' => 'Домашняя страница',
  'Invalid email address' => 'Неправильный адрес email',
  'Invite User' => 'Пригласить пользователя',
  'Level' => 'Уровень',
  'Login Required' => 'Необходима авторизация',
  'My Profile' => 'Мой профиль',
  'Name' => 'Имя',
  'Old Password' => 'Старый пароль',
  'Password' => 'Пароль',
  'Password Reset: Answer' => 'Восстановление пароля: Ответ',
  'Password Reset: Question' => 'Восстановление пароля: Вопрос',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => 'Пожалуйста, введите буквы, изображенные на картинке выше. <br/> Буквы вводятся без учета регистра.',
  'Proceed' => 'В процессе',
  'Recovery Mode' => 'Режим восстановления',
  'Register' => 'Регистрация',
  'Registration Complete, you can now login.' => 'Регистрация завершена, вы можете авторизироваться',
  'Registration Complete. You now have to wait for an admin to approve your account.' => 'Регистрация завершена. Теперь придется ждать администратора, чтобы одобрить ваше внимание.',
  'Remember Me' => 'Запомнить меня на этом компьютере',
  'Request New Password' => 'Запрос нового пароля ',
  'Resend Email' => 'Еще раз отправить письмо',
  'Root Tools' => 'Root Инструменты',
  'Root password must contain at least 2 digits and 2 letters and have at least 5 characters' => 'Рутовый пароль должен содержать по меньшей мере 2 цифры и 2 буквы и иметь не менее 5 символов.',
  'Save' => 'Сохранить',
  'Security' => 'Защита',
  'The requested page does not exist.' => 'Запрошенная страница не найдена.',
  'This account is not approved yet' => 'Учетная запись не подтверждена',
  'Update' => 'Обновить',
  'Update User' => 'Изменить данные пользователя',
  'Update User Profile' => 'Изменить профиль',
  'User Invitation' => 'Приглашение',
  'User List' => 'Список пользователей',
  'User Name' => 'Имя пользователя',
  'User Registration' => 'Регистрация пользователя',
  'Username' => 'Имя пользователя',
  'Users' => 'Пользователи',
  'Verification Code' => 'Код подтверждения',
  'We are sorry, but your account is banned' => 'Мы сожалеем, но ваш аккаунт запрещен.',
  'You are not allowed to update other accounts' => 'Вы не можете изменять другие учетные записи',
  'You didn\'t enter the correct password' => 'Неправильный пароль',
  'profile' => 'профиль',
  'register' => 'регистрация',
  'the confirmation password doesn\'t match the password' => 'пароли не совпадают',
  'the password must be of at least 5 characters' => 'Пароль должен быть не менее 5 символов',
  'the password must contain at least 2 digits and 2 letters and have at least 5 characters' => 'Пароль должен содержать не менее 2 цифры и 2 буквы и иметь не менее 5 символов',
  'the password must contain at least 2 digits, 2 letters and a special character' => 'Пароль должен содержать по меньшей мере 2 цифры, 2 буквы и специальные символы',
  'username must be at least 4 characters and can only be alphanumeric' => 'имя пользователя должно быть не менее 4-х символов и может быть только буквенно-цифровой',
  '{username}\'s Profile' => 'Профиль пользователя {username}',
);
