<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Unable to create the tables in the database. Make sure that your db user has the necessary permissions to create a new table.<br/>This release only officially supports Mysql and PostgreSQL.' => 'Impossibile creare tabelle sul database. Assicurati che l\'utente che stai utilizzando per accedervi abbia i permessi necessari per creare tabelle.<br/>Questa versione supporta ufficialmente solo MySQL e Postgres',
  'You didn\'t correctly set the class property in the user component.<br/>Value set: <b>{class}</b><br/>Value expected: <b>WebUserGroups</b>' => 'Non hai correttamente settato la propriet&agrave; classe nello user component.<br/>Valore attuale: <b>{class}</b><br/>Valore atteso: <b>WebUserGroups</b>',
  'You didn\'t set an adminEmail param inside your application configuration file.' => 'Non hai settato il parametro adminEmail nel tuo file di configurazione',
  'You didn\'t set the access code in your config file.' => 'Non hai settato un accessCode nel tuo file di configurazione',
  '<p>userGroups Installed! To continue the configuration please login</p><p>The new Controller class file has been created. Your old controller has been saved in the component folder with the name <i>_old_Controller.php</i></p>' => '<p>userGroups Installato! Per continuare con la configurazione effettua login</p><p>Il file con la nuova classe Controller &egrave; stato creato. Il tuo vecchio controller &egrave; stato salvato nella cartella component col nome <i>_old_Controller.php</i></p>',
  'Access Code' => 'Codice di Accesso',
  'Error during installation. Couldn\'t create root group with id {id}' => 'Errore durante l\'installazione. Non &egrave stato possibile creare il gruppo di root con id {id}',
  'Error during installation. Couldn\'t create root user with id {id}' => 'Errore durante l\'installazione. Non &egrave stato possibile creare l\'utente di root con id {id}',
  'Password Reset: Question' => 'Reset della Password: Domanda',
  'Retype Root Password' => 'Ripeti la password',
  'Root Email' => 'Indirizzo Email di Root',
  'Root Password' => 'Password di Root',
  'Root User' => 'Utente Root',
  'Setting not installed. Installation abort.' => 'Reset della Password: Risposta',
  'The two access codes don\'t match.' => 'Il codice di accesso non corrisponde',
  'Unable to write the file {path}.' => 'Impossibile scrivere il file {path}',
  'for security reasons the root password must contain at least 2 digits and 2 letters' => 'per ragioni di sicurezza la password di root deve contenere almeno due lettere e due numeri',
  'the Access Code cannot be blank' => 'il codice di accesso non pu&ograve; essere vuoto',
  'the confirmation password doesn\'t match the password' => 'la password di conferma non &egrave; uguale alla password',
);
