<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'This user cannot login in recovery mode.' => 'Этот пользователь не может войти в режим восстановления',
  'A mail to reset your password was sent to the address {email}.' => 'Письмо с инструкциями по восстановлению пароля отправлено на {email}',
  'Input the right answer' => 'Введите правильный ответ',
  'Invalid activation code' => 'Неверный код авторизации',
  'Invalid email address' => 'Неверный e-mail',
  'Password Recovery' => 'Восстановление пароля',
  'User Activation' => 'Активация пользователя',
  'Username not valid' => 'Имя пользователя не существует',
  'wrong user or password.' => 'Неправильный пароль',
);
