<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'A problem occurred during the Data and Access Permission save action' => 'Si &egrave; verificato un problema mentre venivano salvati i dati ed i permessi di accesso',
  'A problem occurred during the configuration save action' => 'Si &egrave; verificato un problema mentre venivano salvate le configurazioni',
  'A problem occurred during the cron jobs configuration save action' => 'Si &egrave; verificato un problema mentre venivano salvati i cron jobs',
  'Cron Jobs Configuration Saved' => 'Salvate le configurazioni dei Cron Jobs',
  'You cannot change the Access Permissions of the Root User' => 'Non puoi cambiare i permessi dell\'utente di Root',
  'You cannot delete a user/group with a higher level then yours.' => 'Non puoi cancellare un utente/gruppo con un livello pi&ugrave; alto del tuo.',
  'You don\'t have the permission to delete any user/group' => 'Non hai i permessi per cancellare alcun utente/gruppo',
  'all' => 'tutti',
  'click here to return to the admin page' => 'clicca qui per tornare alla pagina di admin',
  'click here update userGroups' => 'clicca qui per aggiornare userGroups',
  'if you omit the username the user will be able to chose one upon activation of the account' => 'Se non specifichi un nome utente verr&agrave; richiesto all\'utente di fornirne uno in fase di registrazione',
  'it was not possible to get the value of permissionControl inside your controller. Check your Controller.' => '',
  'update to version {version}' => 'aggiorna alla versione {version}',
  'About the author' => 'Riguardo l\'autore',
  'Ban Period' => 'Durata del Ban',
  'Ban Reason' => 'Motivo del Ban',
  'Controller' => 'Controller',
  'Cron Jobs' => 'Cron Jobs',
  'Cron Jobs successfully removed' => 'Cron Jobs rimossi con successo',
  'Data and Access Permission of <i>{displayname} group</i> changed' => 'Dati e Permessi d\'accesso del <i>gruppo {displayname}</i> cambiati',
  'Data and Access Permission of <i>{displayname} user</i> changed' => 'Dati e Permessi d\'accesso dell\'<i>utente {displayname}</i> cambiati',
  'Description' => 'Descrizione',
  'Do you really want to approve {who} registration?' => 'Vuoi davvero approvare la registrazione di {who}?',
  'Do you really want to ban {who}?' => 'Vuoi davvero bannare {who}?',
  'Do you really want to delete the group {group}?' => 'Vuoi davvero cancellare il gruppo {group}?',
  'Do you really want to delete the user {user}?' => 'Vuoi davvero cancellare l\'utente {user}?',
  'Do you really want to remove those CronJobs?' => 'Vuoi davvero rimuovere quei Cron Job?',
  'Documentation' => 'Documentazione',
  'Element' => 'Elemento',
  'Email Customization' => 'Personalizzazione dei Messaggi Email',
  'First Steps' => 'Primi Passi',
  'Forever' => 'Per Sempre',
  'Group Home: {home}' => 'Home del Gruppo: {home}',
  'Group {groupname}: Data and Access Permissions' => 'Gruppo {groupname}: Dati e Permessi di Accesso',
  'Impossible to delete the requested user/group. An Error Occurred' => 'Impossibile cancellare l\'utente/gruppo richiesto. Si &egrave; verificato un errore',
  'Invalid Request.' => 'Richiesta non Valida',
  'Is this thing safe?' => '&Egrave; sicura questa roba?',
  'Lapse' => 'Giro',
  'Last Execution' => 'Ultima Esecuzione',
  'License' => 'Licenza',
  'Localization' => 'Localizzazione',
  'Main Configurations' => 'Configurazioni Principali',
  'Module' => 'Modulo',
  'New Configurations Saved' => 'Configurazioni Salvate',
  'New Group: Data and Access Permissions' => 'Nuovo Gruppo: Dati e Permessi di Accesso',
  'New User: Data and Access Permissions' => 'Nuovo Utente: Dati e Permessi di Accesso',
  'New group Created.' => 'Nuovo gruppo creato',
  'New user Created.' => 'Nuovo utente creato',
  'Options' => 'Opzioni',
  'Permission' => 'Permessi',
  'Permission granted from Group' => 'Permesso conferito dal gruppo',
  'Profile Extensions' => 'Profile Extensions',
  'Remember if you delete a Group you\'ll delete all the users that belongs to it.' => 'Ricorda che se cancelli un gruppo cancellerai anche tutti gli utenti che ne fanno parte.',
  'Remove not installed CronJobs' => 'Rimuovi i Cron Job non installati',
  'Root Tools' => 'Strumenti di Root',
  'Setting' => 'Settaggi',
  'Setup the new accessControlFilter' => 'Setup del nuovo accessControlFilter',
  'Status' => 'Status',
  'The following problems occurred: {errors}' => 'Si sono verificati i seguenti problemi: {errors}',
  'The requested cron does not exist.' => 'Il cron job richiesto non esiste',
  'The requested rule does not exist.' => 'La regola richiesta non esiste',
  'The requested user/group does not exist and cannot be deleted.' => 'L\'utente/gruppo richiesto non esiste e non pu&ograve; essere cancellato.',
  'This group does not exist' => 'Questo gruppo non esiste',
  'User {username}: Data and Access Permissions' => 'Utente {username}: Dati e Permessi di Accesso',
  'Using the new Access Rules' => 'Utilizzare le nuove Access Rules',
  'Value' => 'Valore',
  'What\'s coming next?' => 'Prossime versioni?',
  'What\'s new?' => 'Cosa c\'&egrave; di nuovo?',
  'You are not allowed to change any configuration' => 'Non sei autorizzato a cambiare alcuna configurazione',
  'You are not allowed to change the cron jobs configuration' => 'Non sei autorizzato a cambiare la configurazione dei Cron Jobs',
  'You are not allowed to remove cron jobs' => 'Non sei autorizzato a rimuovere i Cron Jobs',
  'You cannot assign to a User a Group that has a Level equal or higher then the one you belong to' => 'Non puoi assegnare ad un utente un gruppo che ha un livello uguale o superiore al tuo',
  'You cannot ban a user with a level higher then yours.' => 'Non puoi bannare un utente con un livello pi&ugrave; alto del tuo',
  'You cannot change constant values' => 'Non puoi cambiare i valori costanti',
  'You cannot change data or permissions of Root' => 'Non puoi cambiare Dati o Permessi di Root',
  'You cannot change data or permissions of a user or a group with a level higher then yours' => 'Non puoi cambiare i permessi di accesso di un utente o un gruppo con un livello pi&ugrave; alto del tuo',
  'You cannot create a new user or group' => 'Non puoi creare un nuovo utente o gruppo',
  'You cannot set a Group Level equal or higher then Root' => 'Non puoi settare un livello pari o superiore a quello di Root',
  'You cannot set a Group Level equal or superior to your own' => 'Non puoi settare un livello pari o superiore al tuo',
  'You cannot set this value to a level equal or higher then your own' => 'Non puoi settare questo valore ad un livello pari o superiore al tuo',
  'You didn\'t supply a valid id' => 'L\'id che hai richiesto non &egrave; valido',
  'add group' => 'aggiungi un gruppo',
  'add user' => 'aggiungi un utente',
  'if you omit the password a random one will be generated' => 'Se non specifichi la password ne verr&agrave; generata una a caso',
  'invalid value' => 'valore non valido',
  '{class}.allowAutoLogin must be set true in order to use cookie-based authentication.' => '{class}.allowAutoLogin deve essere settata su true per permettere un autenticazione tramite cookie.',
  '{n} Day|{n} Days' => '{n} giorno|{n} Giorni',
  '{n} Month|{n} Months' => '{n} Mese|{n} Mesi',
  '{n} Week|{n} Weeks' => '{n} Settimana|{n} Settimane',
  '{username}\'s account is banned untill {day}.' => '{username} &egrave; stato bannato fino al {day}',
  '{username}\'s account is now active.' => 'l\'account di {username} &egrave; stato attivato',
  '{what} deleted.' => '{what} cancellato.',
);
