<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'you didn\'t initialize the UGCron singleton' => 'Non hai inizializzato il singleton UGCron',
  'Cronjob not installed' => 'Cron Job non installato',
  'No description found for the requested cron job' => 'Nessuna descrizione trovata per il cron job richiesto',
  'You didn\'t set the cron table name' => 'Non hai settato il nome della Cron Table',
  'You have to provide a name for the cronjob' => 'Devi assegnare un nome al Cron Job',
  'could not install the module. Lapse must be an integer' => 'Non &egrave; stato possibile installare il modulo. Lapse deve essere un intero',
  'delete users who have not been activated for more then 7 days' => 'Cancella gli utenti che non sono stati attivati per pi&ugrave; di 7 giorni',
  'installed and running' => 'Installato e funzionante',
  'not installed' => 'Non installato',
  'reactivate users whose ban period is over' => 'Reattiva gli utenti il cui periodo di ban &egrave; scaduto',
  'the model provided is not an instance of CActiveRecord' => 'Il modello fornito non &egrave; un istanza di CActiveRecord',
  'the provided criteria are not an instance of CDbCriteria' => 'I criteri della query forniti non sono un istanza di CDbCriteria',
  'you didn\'t provide a valid action' => 'Non hai fornito un\'azione valida',
  'you didn\'t set the columns to update' => 'Non hai settato quali colonne aggiornare',
);
