<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'This user cannot login in recovery mode.' => 'Questo utente non pu&ograve; loggare in recovery mode',
  'A mail to reset your password was sent to the address {email}.' => 'Una mail con le istruzioni per resettare la tua password &egrave; stata inviata all\'indirizzo {email}',
  'Input the right answer' => 'Inserisci la risposta corretta',
  'Invalid activation code' => 'Codice di Attivazione non valido',
  'Invalid email address' => 'Indirizzo email non valido',
  'Password Recovery' => 'Recupera la Password',
  'User Activation' => 'Attivazione Utente',
  'Username not valid' => 'Nome utente non valido',
  'wrong user or password.' => 'Nome utente o password errati',
);
