<?php

return array (
  0 => 
  array (
    'id' => 1,
    'lft' => 0,
    'rgt' => 175,
    'level' => 0,
    'name' => 'root',
    'type' => 0,
    'link' => '',
    'controller' => '',
    'action' => '',
    'element' => '0',
    'elementmodel' => '',
  ),
  1 => 
  array (
    'id' => 2,
    'lft' => 145,
    'rgt' => 150,
    'level' => 1,
    'name' => 'Ямы',
    'type' => 0,
    'link' => '',
    'controller' => '',
    'action' => '',
    'element' => NULL,
    'elementmodel' => '',
  ),
  2 => 
  array (
    'id' => 3,
    'lft' => 146,
    'rgt' => 147,
    'level' => 2,
    'name' => 'Поиск ям',
    'type' => 0,
    'link' => '',
    'controller' => 'Holes',
    'action' => 'Index',
    'element' => NULL,
    'elementmodel' => '',
  ),
  3 => 
  array (
    'id' => 4,
    'lft' => 148,
    'rgt' => 149,
    'level' => 2,
    'name' => 'Карта',
    'type' => 0,
    'link' => '',
    'controller' => 'Holes',
    'action' => 'Map',
    'element' => NULL,
    'elementmodel' => '',
  ),
  4 => 
  array (
    'id' => 5,
    'lft' => 151,
    'rgt' => 152,
    'level' => 1,
    'name' => 'Новости',
    'type' => 0,
    'link' => '',
    'controller' => 'News',
    'action' => 'Index',
    'element' => NULL,
    'elementmodel' => '',
  ),
  5 => 
  array (
    'id' => 6,
    'lft' => 153,
    'rgt' => 162,
    'level' => 1,
    'name' => 'Информация',
    'type' => 0,
    'link' => '',
    'controller' => NULL,
    'action' => NULL,
    'element' => NULL,
    'elementmodel' => '',
  ),
  6 => 
  array (
    'id' => 7,
    'lft' => 154,
    'rgt' => 155,
    'level' => 2,
    'name' => 'О проекте',
    'type' => 0,
    'link' => '',
    'controller' => 'Site',
    'action' => 'page',
    'element' => 'about',
    'elementmodel' => 'CViewAction',
  ),
  7 => 
  array (
    'id' => 8,
    'lft' => 156,
    'rgt' => 157,
    'level' => 2,
    'name' => 'Статистика',
    'type' => 0,
    'link' => '',
    'controller' => 'Statics',
    'action' => 'Index',
    'element' => '',
    'elementmodel' => '',
  ),
  8 => 
  array (
    'id' => 9,
    'lft' => 158,
    'rgt' => 159,
    'level' => 2,
    'name' => 'Нормативы',
    'type' => 0,
    'link' => '',
    'controller' => 'Site',
    'action' => 'page',
    'element' => 'regulations',
    'elementmodel' => 'CViewAction',
  ),
  9 => 
  array (
    'id' => 10,
    'lft' => 160,
    'rgt' => 161,
    'level' => 2,
    'name' => 'Справочники',
    'type' => 0,
    'link' => '',
    'controller' => 'Sprav',
    'action' => 'Index',
    'element' => '',
    'elementmodel' => '',
  ),
  10 => 
  array (
    'id' => 11,
    'lft' => 163,
    'rgt' => 166,
    'level' => 1,
    'name' => 'Поддержка',
    'type' => 0,
    'link' => '',
    'controller' => NULL,
    'action' => NULL,
    'element' => NULL,
    'elementmodel' => '',
  ),
  11 => 
  array (
    'id' => 12,
    'lft' => 167,
    'rgt' => 174,
    'level' => 1,
    'name' => 'Чем помочь?',
    'type' => 0,
    'link' => '',
    'controller' => NULL,
    'action' => NULL,
    'element' => NULL,
    'elementmodel' => '',
  ),
  12 => 
  array (
    'id' => 13,
    'lft' => 168,
    'rgt' => 169,
    'level' => 2,
    'name' => 'Деньги',
    'type' => 0,
    'link' => '',
    'controller' => 'Site',
    'action' => 'page',
    'element' => 'donations',
    'elementmodel' => 'CViewAction',
  ),
  13 => 
  array (
    'id' => 14,
    'lft' => 170,
    'rgt' => 173,
    'level' => 2,
    'name' => 'Разработка',
    'type' => 0,
    'link' => '',
    'controller' => NULL,
    'action' => NULL,
    'element' => NULL,
    'elementmodel' => '',
  ),
  14 => 
  array (
    'id' => 15,
    'lft' => 171,
    'rgt' => 172,
    'level' => 3,
    'name' => 'API',
    'type' => 1,
    'link' => 'http://rosyama.ru/api/',
    'controller' => '',
    'action' => '',
    'element' => '',
    'elementmodel' => '',
  ),
  15 => 
  array (
    'id' => 18,
    'lft' => 164,
    'rgt' => 165,
    'level' => 2,
    'name' => 'FAQ',
    'type' => 0,
    'link' => '',
    'controller' => 'Site',
    'action' => 'page',
    'element' => 'faq',
    'elementmodel' => 'CViewAction',
  ),
);